# Generated by Django 4.1.3 on 2022-12-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_despesas_categoria_despesa"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Despesa",
        ),
    ]
