# Generated by Django 4.1.3 on 2022-12-03 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_delete_despesa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="despesas",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.categoria"
            ),
        ),
    ]
