# Generated by Django 4.1.3 on 2022-12-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_categoria_usuario_ganho"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="usuario",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="despesas",
            old_name="usuario",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="ganho",
            old_name="usuario",
            new_name="user",
        ),
    ]
